version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: express-rate-limit
    versions:
    - 5.2.3
    - 5.2.5
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: celebrate
    versions:
    - 13.0.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: validator
    versions:
    - 13.5.2
